sudo: false
language: scala
script: "sbt clean coverage test"
after_success:
  - "sbt coverageReport coverageAggregate"
  - "sbt coveralls"
scala:
  - "2.11.11"
  - "2.12.0"
jdk:
  - oraclejdk8

before_install:
  - ./install-redis.sh
  - gem install redis
env:
  global:  
    - SBT_OPTS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M"
    - REDIS_HOME=redis-3.2.0/src
# whitelist
branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2
