language: scala
script: sbt ++$TRAVIS_SCALA_VERSION "test"
after_script:
  - "sbt coveralls"
scala:
  - "2.10.2"
jdk:
  - oraclejdk7
  - openjdk7
services:
  - redis
env:
  - SBT_OPTS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M"
